language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - python setup.py install
script:
    - py.test autograd/tests --doctest-modules --cov-report term-missing --cov autograd
after_success:
    - coveralls
