language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    
install:
  - python setup.py install
script:
    - pytest
after_success:
    - coveralls
